name: General Question
description: Ask a question about running the gamemode for yourself
labels: ["question"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        **Have a question about running the gamemode?** ❓🚀
        We're here to help! Please provide as much detail as possible so we can assist you effectively.

  - type: input
    id: question-title
    attributes:
      label: Question Title
      description: |
        Give your question a clear and descriptive title.
      placeholder: E.g., "How do I set up the gamemode on my local machine?"
    validations:
      required: true

  - type: textarea
    id: question-body
    attributes:
      label: Question
      description: |
        Describe your question in detail.
      placeholder: E.g., "I'm having trouble setting up the gamemode on my local machine. Can you provide a step-by-step guide?"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: |
        Provide any context or background information that might help us understand your question better.
      placeholder: E.g., "I'm using Windows 10, have Node.js and PostgreSQL installed, and followed the initial setup guide."
    validations:
      required: false

  - type: textarea
    id: troubleshooting
    attributes:
      label: Troubleshooting Steps
      description: |
        List any troubleshooting steps you've already taken.
      placeholder: E.g., "I checked the server logs for errors and ensured all dependencies are installed."
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: |
        Any other details you think are important?
